---
- hosts: local
  gather_facts: false
  become_user: root
  become: true
  
  tasks:

  - include_tasks: includes/find_ucp.yml #ping_servers="{{ groups.ucp }}" 
  
  - debug: var=ucp_instance
    when: _debug is defined
    
    
#
# Retrieve and remember a Token for using the UCP API
#
  - name: Retrieve a token for the UCP API
    uri:
      url: "https://{{ ucp_instance }}.{{ domain_name }}/auth/login"
      headers:
        Content-Type: application/json
      method: POST
      status_code: 200
      body_format: json
      validate_certs: no
      body: '{"username":"{{ ucp_username }}","password":"{{ ucp_password }}"}'
      use_proxy: no
    register: login
    until: login.status == 200
    retries: 20
    delay: 5

  - name: Remember the token
    set_fact:
      auth_token:  "{{ login.json.auth_token }}"

  - name: Creates directory
    file: path=~/certs.{{ ucp_username }} state=directory

  - block:
    - include_tasks: includes/config_client.yml
    become: true
    
  #- include_tasks: includes/config_client.yml   
  
  
  - name: Test client
    shell: |
      . env.sh
      docker ps
    args:
      chdir: ~/certs.{{ ucp_username }}
      executable: /usr/bin/bash
  
